In [ ]:
# Python Numpy Tutorial for Beginners by freeCodeCamp.org

# Numpy is faster than list.

In [1]:
# pip install numpy
import numpy as np

In [22]:
#The Basics

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
b= np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [7]:
#Get dimension

a.ndim

1

In [8]:
b.ndim

2

In [10]:
#Get shape

a.shape

(3,)

In [11]:
b.shape

(2, 3)

In [12]:
#Get type

a.dtype

dtype('int64')

In [13]:
b.dtype

dtype('float64')

In [14]:
x = np.array([1,2,3], dtype='int16')
x.dtype

dtype('int16')

In [15]:
#Get size
a.itemsize

8

In [16]:
b.itemsize

8

In [17]:
x.itemsize

2

In [18]:
y=np.array([1,2,3], dtype='int32')
y.itemsize

4

In [20]:
#Get total size
a.size * a.itemsize

24

In [21]:
a.nbytes

24

In [23]:
#Accessing/Changing specific elements,rows,columns, etc.

a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [24]:
a.shape

(2, 7)

In [25]:
#Get a specific element [r,c]
#Start indexing from 0 for both row and column

a[1,5]

13

In [26]:
a[1, -2]

13

In [27]:
#Get a specific row:

a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
#Get a specofoc column
a[:,2]

array([ 3, 10])

In [29]:
#Getting a little mpre fancy[starting index:end index:step size]

#First row, start from 1, end 6, step size 2

a[0,1:6:2]

array([2, 4, 6])

In [31]:
a[0,1:-1:2]

array([2, 4, 6])

In [32]:
#Change an element

a[1,5] = 20 #it was 13, now 20.

a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [33]:
# change all elements in a column to 5:

a[:,2] = 5

a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [35]:
a[:,2] = [1,2]

print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [36]:
#3-D example

b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
#Get specific element(work outside in)

b[0,1,1]

4

In [39]:
b[1,1,1]

8

In [40]:
b[1,0,0]

5

In [41]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [42]:
#replace 

b[:,1,:] =[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [ ]:
#Initializing Different Types of Arrays

In [45]:
# All 0s matrix

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [46]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [48]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [49]:
#All 1s matrix

np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [50]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [51]:
#All other number

np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [52]:
np.full((2,2),99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [53]:
#All other number (full_like)

np.full_like(a.shape, 4)

array([4, 4])

In [54]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [56]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [57]:
#Random decimal numbers
np.random.rand(4,2) 

array([[0.34205354, 0.74701758],
       [0.59103886, 0.28249108],
       [0.6910541 , 0.91151783],
       [0.63962398, 0.39104544]])

In [58]:
np.random.rand(4,2,3) 

array([[[0.36997182, 0.50175035, 0.1239616 ],
        [0.58534647, 0.1549043 , 0.14607868]],

       [[0.09110408, 0.20471374, 0.42321855],
        [0.31847808, 0.25858878, 0.67668307]],

       [[0.29630265, 0.6456499 , 0.05033121],
        [0.86251003, 0.15813899, 0.72082822]],

       [[0.00314813, 0.5376219 , 0.3106839 ],
        [0.20282836, 0.70471905, 0.08138685]]])

In [60]:
np.random.random_sample(a.shape) 

array([[0.71806419, 0.26928722, 0.41200683, 0.52366168, 0.27817691,
        0.30843729, 0.43863032],
       [0.79069971, 0.4932733 , 0.8226693 , 0.55839788, 0.14541132,
        0.39361848, 0.46089191]])

In [61]:
#random integer values

np.random.randint(7) 

2

In [62]:
np.random.randint(7, size=(3,3)) 

array([[0, 4, 0],
       [2, 2, 3],
       [0, 5, 3]])

In [63]:
np.random.randint(4, 7, size=(3,3)) 

array([[6, 5, 6],
       [4, 5, 6],
       [6, 5, 6]])

In [64]:
np.random.randint(-4, 8, size=(3,3)) 

array([[ 5, -3, -3],
       [-1, -1, -3],
       [ 6, -1,  2]])

In [65]:
#The identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [68]:
arr = np.array([1,2,3])

r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [71]:
arr2 = np.array([[1,2,3]])
r2 = np.repeat(arr2,3, axis=0)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [72]:
 r3 = np.repeat(arr2,3, axis=1)
print(r3)

[[1 1 1 2 2 2 3 3 3]]


In [82]:
#ex1:

mat = np.ones((5,5), dtype='int32')
mat[1:4,1:4]=0
mat[2,2]=9
print(mat)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


##### Be careful copying arrays!

In [84]:
a = np.array([1,2,3])

b= a.copy() # does not change the original a
b[0] = 100

print(b)
print(a)

[100   2   3]
[1 2 3]


In [85]:
x = np.array([1,2,3])

y= x # does change the original x
y[0] = 100

print(y)
print(x)

[100   2   3]
[100   2   3]


##### Mathematics

In [86]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [87]:
a+2

array([3, 4, 5, 6])

In [88]:
a-2

array([-1,  0,  1,  2])

In [89]:
a*2

array([2, 4, 6, 8])

In [90]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [91]:
b= np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [92]:
a ** 2

array([ 1,  4,  9, 16])

In [93]:
#Take the sin values of a

np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [94]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [97]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [99]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [101]:
# Find the determinant

c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [102]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
np.min(stats)

1

In [105]:
np.min(stats, axis=1)

array([1, 4])

In [106]:
np.min(stats, axis=0)

array([1, 2, 3])

In [104]:
np.max(stats)

6

In [107]:
np.max(stats, axis=0)

array([4, 5, 6])

In [108]:
np.max(stats, axis=1)

array([3, 6])

In [109]:
np.sum(stats)

21

In [110]:
np.sum(stats, axis=1)

array([ 6, 15])

In [111]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [116]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
before.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [117]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [118]:
after2 = before.reshape((2,2,2))
print(after2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [120]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [121]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [122]:
# Horizontal stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

In [124]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [129]:
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [128]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [130]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

## You can index with a list in Numpy

In [131]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [132]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [133]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [134]:
np.all(filedata > 50, axis=1)

array([False, False, False])

In [135]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [136]:
# ~ means NOT
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [147]:

mat = np.arange(1,31,dtype='int32')
mat = mat.reshape(6,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [149]:
# ex2:
print(mat[2:4, 0:2])

[[11 12]
 [16 17]]


In [150]:
# ex3:

print(mat[[0,1,2,3],[1,2,3,4]])

[ 2  8 14 20]


In [151]:
# ex4:

print(mat[[0,4,5],3:])

[[ 4  5]
 [24 25]
 [29 30]]
